import { optimizeCloudinaryUrl } from './cloudinaryImage';

// Static require() map for locally-bundled product images, keyed by the exact
// product `name` string in the Firestore `products` collection. 114 entries are the
// original catalog's photos (customer/assets/Cleaned_Products, background-removed and
// styled via the project's established pipeline). 166 more were added from manually
// sourced photos (customer/assets/New_Products) for the newer 196-item catalog, matched
// by hand against actual packaging (filenames in that source folder carry no product
// info), then run through the same pipeline: AI background removal (skipped for any
// source photo that already had real transparency -- re-running it risks eating into the
// product itself), crop to content, padded, upscaled to 1080px, sharpened. 17 products in
// the newer catalog have no photo here -- no usable source photo existed for them (some
// candidates were watermarked recipe photos of a cooked dish, a different product
// category entirely, or simply weren't provided) -- and 2 more (White Kadala / Black
// Benny, Bourbon Neapolitan Cream) were explicitly held back. All of these fall through
// to the placeholder icon below rather than showing an incorrect image.
//
// Metro requires require() paths to be static, and the target file must exist at bundle
// time -- so this map can only reference files that are actually present in
// assets/Cleaned_Products/. Not every product has a local photo; callers must fall back
// to the product's remote `images` URL (or a placeholder icon) when a name isn't present
// here. See getProductImageSource() below.

const productImages = {
  "Local Greens (Bal Chambu)": require("../../assets/Cleaned_Products/Local Greens Bal Chambu.png"),
  "Vada Paruppu (Urad Dal)": require("../../assets/Cleaned_Products/Vada Paruppu Urad Dal.png"),
  "Dream Cream Orange / Cashewnut": require("../../assets/Cleaned_Products/Dream Cream Orange Cashewnut.png"),
  "Ginger": require("../../assets/Cleaned_Products/Ginger.png"),
  "Dates Syrup": require("../../assets/Cleaned_Products/Dates Syrup.png"),
  "TT Asafoetida Cake": require("../../assets/Cleaned_Products/TT Asafoetida Cake.png"),
  "Power Soap": require("../../assets/Cleaned_Products/Power Soap.png"),
  "Milma Ghee": require("../../assets/Cleaned_Products/Milma Ghee.png"),
  "Sunfeast Golden Bakery": require("../../assets/Cleaned_Products/Sunfeast Golden Bakery.png"),
  "Lia Agarbathy (Apple/Rose/Lavender/Jasmine)": require("../../assets/Cleaned_Products/Lia Agarbathy Apple Rose Lavender Jasmine.png"),
  "Tiger KR Coconut": require("../../assets/Cleaned_Products/Tiger KR Coconut.png"),
  "Mango": require("../../assets/Cleaned_Products/Mango.png"),
  "50-50 Biscuits": require("../../assets/Cleaned_Products/50-50 Biscuits.png"),
  "786 Surekha Rice": require("../../assets/Cleaned_Products/786 Surekha Rice.png"),
  "Anus Chilly Sauce": require("../../assets/Cleaned_Products/Anus Chilly Sauce.png"),
  "Anus Chukku Kappi (Ginger Coffee Mix)": require("../../assets/Cleaned_Products/Anus Chukku Kappi Ginger Coffee Mix.png"),
  "Anus Dates Pickle": require("../../assets/Cleaned_Products/Anus Dates Pickle.png"),
  "Anus Lemon Pickle": require("../../assets/Cleaned_Products/Anus Lemon Pickle.png"),
  "Anus Mango Pickle": require("../../assets/Cleaned_Products/Anus Mango Pickle.png"),
  "Anus Soya Sauce": require("../../assets/Cleaned_Products/Anus Soya Sauce.png"),
  "Anus Tender Mango Pickle": require("../../assets/Cleaned_Products/Anus Tender Mango Pickle.png"),
  "Anus Tomatto Sauce": require("../../assets/Cleaned_Products/Anus Tomatto Sauce.png"),
  "AVT Premium Tea": require("../../assets/Cleaned_Products/AVT Premium Tea.png"),
  "Bakers Kasuri Methi": require("../../assets/Cleaned_Products/Bakers Kasuri Methi.png"),
  "Banana Flower (Ullie Poo)": require("../../assets/Cleaned_Products/Banana Flower Ullie Poo.png"),
  "Beans": require("../../assets/Cleaned_Products/Beans.png"),
  "Beet Root": require("../../assets/Cleaned_Products/Beet Root.png"),
  "Bharath Doppi Rice": require("../../assets/Cleaned_Products/Bharath Doppi Rice.png"),
  "Black Pepper Powder": require("../../assets/Cleaned_Products/Black Pepper Powder.png"),
  "Boost 200 gm Pouch": require("../../assets/Cleaned_Products/Boost 200 gm Pouch.png"),
  "Boost 500 gm Jar": require("../../assets/Cleaned_Products/Boost 500 gm Jar.png"),
  "Bounty (S.Bounty)": require("../../assets/Cleaned_Products/Bounty S.Bounty.png"),
  "Brinjal": require("../../assets/Cleaned_Products/Brinjal.png"),
  "Bru Coffee Instant": require("../../assets/Cleaned_Products/Bru Coffee Instant.png"),
  "Bru Coffee Pure": require("../../assets/Cleaned_Products/Bru Coffee Pure.png"),
  "Capsicum (Green)": require("../../assets/Cleaned_Products/Capsicum Green.png"),
  "Carrot": require("../../assets/Cleaned_Products/Carrot.png"),
  "Cashew Split": require("../../assets/Cleaned_Products/Cashew Split.png"),
  "Cheru Paruppu (Moong Dal)": require("../../assets/Cleaned_Products/Cheru Paruppu Moong Dal.png"),
  "Chicken Masala Powder": require("../../assets/Cleaned_Products/Chicken Masala Powder.png"),
  "Chilli Powder": require("../../assets/Cleaned_Products/Chilli Powder.png"),
  "Chocolate Horlicks Refill 1Kg": require("../../assets/Cleaned_Products/Chocolate Horlicks Refill 1Kg.png"),
  "Chocolate Horlicks Sachet 75g": require("../../assets/Cleaned_Products/Chocolate Horlicks Sachet 75g.png"),
  "Clear Hair Oil 75ml": require("../../assets/Cleaned_Products/Clear Hair Oil 75ml.png"),
  "Clinic Plus Hair Shampoo": require("../../assets/Cleaned_Products/Clinic Plus Hair Shampoo.png"),
  "Clinic Plus Hair Shampoo Straight & Shine 175ml": require("../../assets/Cleaned_Products/Clinic Plus Hair Shampoo Straight and Shine 175ml.png"),
  "Clinic Plus Hair Shampoo Strong & Extra Thick 175ml": require("../../assets/Cleaned_Products/Clinic Plus Hair Shampoo Strong and Extra Thick 175ml.png"),
  "Clinic Plus Hair Shampoo Strong & Shine 6ml": require("../../assets/Cleaned_Products/Clinic Plus Hair Shampoo Strong and Shine 6ml.png"),
  "Clinic Plus Hair Shampoo Strong Scalp": require("../../assets/Cleaned_Products/Clinic Plus Hair Shampoo Strong Scalp.png"),
  "Clinic Plus Strong And Smooth 6ml": require("../../assets/Cleaned_Products/Clinic Plus Strong And Smooth 6ml.png"),
  "Close Up Toothpaste Deep Action Red Hot Gel 26g": require("../../assets/Cleaned_Products/Close Up Toothpaste Deep Action Red Hot Gel 26g.png"),
  "Close Up Toothpaste Ever Fresh Red Hot Gel 40g": require("../../assets/Cleaned_Products/Close Up Toothpaste Ever Fresh Red Hot Gel 40g.png"),
  "Comfort Fabric Conditioner Blue 220ml": require("../../assets/Cleaned_Products/Comfort Fabric Conditioner Blue 220ml.png"),
  "Comfort Fabric Conditioner Pink 220ml": require("../../assets/Cleaned_Products/Comfort Fabric Conditioner Pink 220ml.png"),
  "Coriander Leaves (Malli)": require("../../assets/Cleaned_Products/Coriander Leaves Malli.png"),
  "Coriander Powder": require("../../assets/Cleaned_Products/Coriander Powder.png"),
  "Cucumber": require("../../assets/Cleaned_Products/Cucumber.png"),
  "Cumin (Jeera) Powder": require("../../assets/Cleaned_Products/Cumin Jeera Powder.png"),
  "Curry Leaves (K. Leaves)": require("../../assets/Cleaned_Products/Curry Leaves K. Leaves.png"),
  "Cycle 3-in-1 Agarbathi": require("../../assets/Cleaned_Products/Cycle 3-in-1 Agarbathi.png"),
  "Dabur Almond Hair Oil": require("../../assets/Cleaned_Products/Dabur Almond Hair Oil.png"),
  "Dabur Amla Hair Oil": require("../../assets/Cleaned_Products/Dabur Amla Hair Oil.png"),
  "Dabur Glucose": require("../../assets/Cleaned_Products/Dabur Glucose.png"),
  "Dabur Red Toothpaste": require("../../assets/Cleaned_Products/Dabur Red Toothpaste.png"),
  "Dabur Vatika Hair Oil": require("../../assets/Cleaned_Products/Dabur Vatika Hair Oil.png"),
  "Dark Fantasy Bourbon": require("../../assets/Cleaned_Products/Dark Fantasy Bourbon.png"),
  "Dark Fantasy Vanilla": require("../../assets/Cleaned_Products/Dark Fantasy Vanilla.png"),
  "Devon Chilly Powder": require("../../assets/Cleaned_Products/Devon Chilly Powder.png"),
  "Devon Coriander Powder": require("../../assets/Cleaned_Products/Devon Coriander Powder.png"),
  "Devon Corn Starch (household/cooking use)": require("../../assets/Cleaned_Products/Devon Corn Starch household cooking use.png"),
  "DH Corn Flour": require("../../assets/Cleaned_Products/DH Corn Flour.png"),
  "DH Easy Idiyappam": require("../../assets/Cleaned_Products/DH Easy Idiyappam.png"),
  "DH Idiyappam / Appam Podi": require("../../assets/Cleaned_Products/DH Idiyappam Appam Podi.png"),
  "DH Macroni": require("../../assets/Cleaned_Products/DH Macroni.png"),
  "DH Palada Payasam Mix": require("../../assets/Cleaned_Products/DH Palada Payasam Mix.png"),
  "DH Roast Ragi Powder": require("../../assets/Cleaned_Products/DH Roast Ragi Powder.png"),
  "DH Turmeric Powder": require("../../assets/Cleaned_Products/DH Turmeric Powder.png"),
  "DH Vermicelli Mix": require("../../assets/Cleaned_Products/DH Vermicelli Mix.png"),
  "DH White Puttu Podi": require("../../assets/Cleaned_Products/DH White Puttu Podi.png"),
  "Dolphin IR8 Pachari Rice": require("../../assets/Cleaned_Products/Dolphin IR8 Pachari Rice.png"),
  "Dove Bathing Soap Cream Beauty 50g": require("../../assets/Cleaned_Products/Dove Bathing Soap Cream Beauty 50g.png"),
  "Dove Daily Shine Shampoo & Conditioner Twin Sachet": require("../../assets/Cleaned_Products/Dove Daily Shine Shampoo and Conditioner Twin Sachet.png"),
  "Dove Glycolic Hydration Mid Shampoo 180ml": require("../../assets/Cleaned_Products/Dove Glycolic Hydration Mid Shampoo 180ml.png"),
  "Dove Hair Conditioner Daily Shine": require("../../assets/Cleaned_Products/Dove Hair Conditioner Daily Shine.png"),
  "Dove Hair Conditioner Dryness Care 80ml": require("../../assets/Cleaned_Products/Dove Hair Conditioner Dryness Care 80ml.png"),
  "Dove Hair Conditioner Hair Fall Rescue": require("../../assets/Cleaned_Products/Dove Hair Conditioner Hair Fall Rescue.png"),
  "Dove Hair Conditioner Intense Damage Therapy": require("../../assets/Cleaned_Products/Dove Hair Conditioner Intense Damage Therapy.png"),
  "Dove Hair Shampoo & Conditioner Hair Fall Therapy": require("../../assets/Cleaned_Products/Dove Hair Shampoo and Conditioner Hair Fall Therapy.png"),
  "Dove Hair Shampoo & Conditioner Intense Repair": require("../../assets/Cleaned_Products/Dove Hair Shampoo and Conditioner Intense Repair.png"),
  "Dove Hair Shampoo Anti Dandruff Therapy": require("../../assets/Cleaned_Products/Dove Hair Shampoo Anti Dandruff Therapy.png"),
  "Dove Hair Shampoo Clean & Fresh 6ml": require("../../assets/Cleaned_Products/Dove Hair Shampoo Clean and Fresh 6ml.png"),
  "Dove Hair Shampoo Daily Shine": require("../../assets/Cleaned_Products/Dove Hair Shampoo Daily Shine.png"),
  "Dove Hair Shampoo Dandruff Care 80ml": require("../../assets/Cleaned_Products/Dove Hair Shampoo Dandruff Care 80ml.png"),
  "Dove Hair Shampoo Dryness Care 80ml": require("../../assets/Cleaned_Products/Dove Hair Shampoo Dryness Care 80ml.png"),
  "Dove Hair Shampoo Hair Fall Rescue 80ml": require("../../assets/Cleaned_Products/Dove Hair Shampoo Hair Fall Rescue 80ml.png"),
  "Dove Hair Shampoo Hair Fall Therapy": require("../../assets/Cleaned_Products/Dove Hair Shampoo Hair Fall Therapy.png"),
  "Dove Hair Shampoo Healthy Ritual For Growing Hair": require("../../assets/Cleaned_Products/Dove Hair Shampoo Healthy Ritual For Growing Hair.png"),
  "Dove Hair Shampoo Intense Repair": require("../../assets/Cleaned_Products/Dove Hair Shampoo Intense Repair.png"),
  "Dove Men+ Care Ad 2In1 Shampoo+Conditioner": require("../../assets/Cleaned_Products/Dove Men Plus Care Ad 2In1 Shampoo Plus Conditioner.png"),
  "Dove Pink Serum Beauty Bar": require("../../assets/Cleaned_Products/Dove Pink Serum Beauty Bar.png"),
  "Drumstick (Salladu)": require("../../assets/Cleaned_Products/Drumstick Salladu.png"),
  "E-fee Washing Liquid": require("../../assets/Cleaned_Products/E-fee Washing Liquid.png"),
  "Egg Masala Powder": require("../../assets/Cleaned_Products/Egg Masala Powder.png"),
  "Elite Atta": require("../../assets/Cleaned_Products/Elite Atta.png"),
  "Elite Maida": require("../../assets/Cleaned_Products/Elite Maida.png"),
  "Elite Rava": require("../../assets/Cleaned_Products/Elite Rava.png"),
  "Elite Rice Puttu Podi": require("../../assets/Cleaned_Products/Elite Rice Puttu Podi.png"),
  "Exo Dishwash Bar": require("../../assets/Cleaned_Products/Exo Dishwash Bar.png"),
  "Flowers (assorted, for pooja)": require("../../assets/Cleaned_Products/Flowers assorted, for pooja.png"),
  "Garam Masala Powder": require("../../assets/Cleaned_Products/Garam Masala Powder.png"),
  "Ginger Garlic Paste": require("../../assets/Cleaned_Products/Ginger Garlic Paste.png"),
  "Ginger Pickle": require("../../assets/Cleaned_Products/Ginger Pickle.png"),
  "Glow & Lovely Facewash Fairness 50g": require("../../assets/Cleaned_Products/Glow and Lovely Facewash Fairness 50g.png"),
  "Gold Walnut": require("../../assets/Cleaned_Products/Gold Walnut.png"),
  "Good Day Butter": require("../../assets/Cleaned_Products/Good Day Butter.png"),
  "Good Day Cashew": require("../../assets/Cleaned_Products/Good Day Cashew.png"),
  "Good Day Chocochip": require("../../assets/Cleaned_Products/Good Day Chocochip.png"),
  "Good Day Pista Badam": require("../../assets/Cleaned_Products/Good Day Pista Badam.png"),
  "Gooseberry (Nelli Kai)": require("../../assets/Cleaned_Products/Gooseberry Nelli Kai.png"),
  "Green Chilly": require("../../assets/Cleaned_Products/Green Chilly.png"),
  "Green Peas 1st": require("../../assets/Cleaned_Products/Green Peas 1st.png"),
  "Hamam Soap": require("../../assets/Cleaned_Products/Hamam Soap.png"),
  "Hellmann's Mayo Smoky Tandoori 85g": require("../../assets/Cleaned_Products/Hellmann's Mayo Smoky Tandoori 85g.png"),
  "Hellmann's Sauce Mayonnaise Doy Pack 85g": require("../../assets/Cleaned_Products/Hellmann's Sauce Mayonnaise Doy Pack 85g.png"),
  "Horlicks Plain Biscuits 45g": require("../../assets/Cleaned_Products/Horlicks Plain Biscuits 45g.png"),
  "Horlicks Ready-to-Drink 125ml Chocolate": require("../../assets/Cleaned_Products/Horlicks Ready-to-Drink 125ml Chocolate.png"),
  "Idiyappam Podi (steamed)": require("../../assets/Cleaned_Products/Idiyappam Podi steamed.png"),
  "Indulekha Hair Shampoo Bringha Hair Fall Cleanser": require("../../assets/Cleaned_Products/Indulekha Hair Shampoo Bringha Hair Fall Cleanser.png"),
  "Kadala Mavu (Chickpea Flour)": require("../../assets/Cleaned_Products/Kadala Mavu Chickpea Flour.png"),
  "Kadala Paruppu (Chana Dal)": require("../../assets/Cleaned_Products/Kadala Paruppu Chana Dal.png"),
  "Kashmiri Chilli Powder": require("../../assets/Cleaned_Products/Kashmiri Chilli Powder.png"),
  "Kellogg's Chocos": require("../../assets/Cleaned_Products/Kellogg's Chocos.png"),
  "Kellogg's Corn Flakes": require("../../assets/Cleaned_Products/Kellogg's Corn Flakes.png"),
  "Kismiss Medium (Raisins Seedless)": require("../../assets/Cleaned_Products/Kismiss Medium Raisins Seedless.png"),
  "Kissan Hari Chutney 100g Doy": require("../../assets/Cleaned_Products/Kissan Hari Chutney 100g Doy.png"),
  "Kissan Imli Khajoor Chutney 100g Doy": require("../../assets/Cleaned_Products/Kissan Imli Khajoor Chutney 100g Doy.png"),
  "Kissan Jam Mixed Fruit 100g": require("../../assets/Cleaned_Products/Kissan Jam Mixed Fruit 100g.png"),
  "Kissan Jam Orange Marmalade 500g": require("../../assets/Cleaned_Products/Kissan Jam Orange Marmalade 500g.png"),
  "Kissan Ketchup Fresh Tomato Chotu 90g": require("../../assets/Cleaned_Products/Kissan Ketchup Fresh Tomato Chotu 90g.png"),
  "Kissan Lehsun Mirch Chutney 100g Doy": require("../../assets/Cleaned_Products/Kissan Lehsun Mirch Chutney 100g Doy.png"),
  "Kit Kat Miniatures": require("../../assets/Cleaned_Products/Kit Kat Miniatures.png"),
  "Kitchen King BT Rice": require("../../assets/Cleaned_Products/Kitchen King BT Rice.png"),
  "Knorr Cream of Broccoli Cup-A-Soup 12.5g": require("../../assets/Cleaned_Products/Knorr Cream of Broccoli Cup-A-Soup 12.5g.png"),
  "Knorr Cup A Soup Instant Hot & Sour 11g": require("../../assets/Cleaned_Products/Knorr Cup A Soup Instant Hot and Sour 11g.png"),
  "Knorr Cup A Soup Instant Manchow 12g": require("../../assets/Cleaned_Products/Knorr Cup A Soup Instant Manchow 12g.png"),
  "Knorr Cup A Soup Instant Mix Vegetable 18g": require("../../assets/Cleaned_Products/Knorr Cup A Soup Instant Mix Vegetable 18g.png"),
  "Knorr Cup A Soup Instant Sweet Corn 10g": require("../../assets/Cleaned_Products/Knorr Cup A Soup Instant Sweet Corn 10g.png"),
  "Knorr Cup A Soup Instant Tomato Chatpata 16g": require("../../assets/Cleaned_Products/Knorr Cup A Soup Instant Tomato Chatpata 16g.png"),
  "KP Herbal Paste": require("../../assets/Cleaned_Products/KP Herbal Paste.png"),
  "KPR Jaya Rice": require("../../assets/Cleaned_Products/KPR Jaya Rice.png"),
  "Ladies Finger": require("../../assets/Cleaned_Products/Ladies Finger.png"),
  "Lemon": require("../../assets/Cleaned_Products/Lemon.png"),
  "Lifebuoy Bathing Soap Care 100% Stronger Germ Protection": require("../../assets/Cleaned_Products/Lifebuoy Bathing Soap Care 100% Stronger Germ Protection.png"),
  "Lifebuoy Bathing Soap Lemon Fresh": require("../../assets/Cleaned_Products/Lifebuoy Bathing Soap Lemon Fresh.png"),
  "Lifebuoy Bathing Soap Total 10 4x65g": require("../../assets/Cleaned_Products/Lifebuoy Bathing Soap Total 10 4x65g.png"),
  "Lifebuoy Bathing Soap Turmeric And Honey": require("../../assets/Cleaned_Products/Lifebuoy Bathing Soap Turmeric And Honey.png"),
  "Lifebuoy Hand Wash Powder to Liquid 10g": require("../../assets/Cleaned_Products/Lifebuoy Hand Wash Powder to Liquid 10g.png"),
  "Lifebuoy Ice Bath 65g x 4": require("../../assets/Cleaned_Products/Lifebuoy Ice Bath 65g x 4.png"),
  "Lifebuoy Neem & Aloe Soap": require("../../assets/Cleaned_Products/Lifebuoy Neem and Aloe Soap.png"),
  "Lifebuoy Total Protect": require("../../assets/Cleaned_Products/Lifebuoy Total Protect.png"),
  "Lipton Clear And Light J&A 100g": require("../../assets/Cleaned_Products/Lipton Clear And Light J and A 100g.png"),
  "Lipton Green Tea Bags Honey Lemon 10 Pcs": require("../../assets/Cleaned_Products/Lipton Green Tea Bags Honey Lemon 10 Pcs.png"),
  "Lipton Green Tea Clear & Light 10s TB": require("../../assets/Cleaned_Products/Lipton Green Tea Clear and Light 10s TB.png"),
  "Lipton Green Tea Honey Lemon 100g": require("../../assets/Cleaned_Products/Lipton Green Tea Honey Lemon 100g.png"),
  "Liril Bathing Soap Lime 75g": require("../../assets/Cleaned_Products/Liril Bathing Soap Lime 75g.png"),
  "Long Beans (Payeru)": require("../../assets/Cleaned_Products/Long Beans Payeru.png"),
  "Lux Advanced Bright Glow": require("../../assets/Cleaned_Products/Lux Advanced Bright Glow.png"),
  "Lux Bathing Soap Fresh Flash Water Lily & Cooling": require("../../assets/Cleaned_Products/Lux Bathing Soap Fresh Flash Water Lily and Cooling.png"),
  "Lux Bathing Soap International Creamy Perfume": require("../../assets/Cleaned_Products/Lux Bathing Soap International Creamy Perfume.png"),
  "Lux Bathing Soap Soft Touch 4 x 60g": require("../../assets/Cleaned_Products/Lux Bathing Soap Soft Touch 4 x 60g.png"),
  "Lux Bathing Soap Velvet Touch Jasmine And Almond": require("../../assets/Cleaned_Products/Lux Bathing Soap Velvet Touch Jasmine And Almond.png"),
  "Lux Glow Bar Collection": require("../../assets/Cleaned_Products/Lux Glow Bar Collection.png"),
  "Lux Sandal Rs10 MLP": require("../../assets/Cleaned_Products/Lux Sandal Rs10 MLP.png"),
  "Maggi 2-Minute Noodles": require("../../assets/Cleaned_Products/Maggi 2-Minute Noodles.png"),
  "Maggi Pazzta": require("../../assets/Cleaned_Products/Maggi Pazzta.png"),
  "Maharaja Orid Dhall": require("../../assets/Cleaned_Products/Maharaja Orid Dhall.png"),
  "Marie Gold": require("../../assets/Cleaned_Products/Marie Gold.png"),
  "Maxo Coil (Mosquito Repellent)": require("../../assets/Cleaned_Products/Maxo Coil Mosquito Repellent.png"),
  "Maxo Genius Combi": require("../../assets/Cleaned_Products/Maxo Genius Combi.png"),
  "Meat Masala Powder": require("../../assets/Cleaned_Products/Meat Masala Powder.png"),
  "Medimix Soap": require("../../assets/Cleaned_Products/Medimix Soap.png"),
  "Milk Bikis Milk Cream": require("../../assets/Cleaned_Products/Milk Bikis Milk Cream.png"),
  "Milk Rusk / Premium Bake Rusk": require("../../assets/Cleaned_Products/Milk Rusk Premium Bake Rusk.png"),
  "Milk Rusk Restage": require("../../assets/Cleaned_Products/Milk Rusk Restage.png"),
  "Milma Butter": require("../../assets/Cleaned_Products/Milma Butter.png"),
  "Milma Ghee Cake": require("../../assets/Cleaned_Products/Milma Ghee Cake.png"),
  "Milma Ghee Cake / Choco Brownie": require("../../assets/Cleaned_Products/Milma Ghee Cake Choco Brownie.png"),
  "Milma Paneer": require("../../assets/Cleaned_Products/Milma Paneer.png"),
  "Mint Leaves (Puthina)": require("../../assets/Cleaned_Products/Mint Leaves Puthina.png"),
  "Munch Chocolate Wafer": require("../../assets/Cleaned_Products/Munch Chocolate Wafer.png"),
  "Mutton Masala Powder": require("../../assets/Cleaned_Products/Mutton Masala Powder.png"),
  "NC Cracker Lite": require("../../assets/Cleaned_Products/NC Cracker Lite.png"),
  "NC Thin Arrowroot Biscuit": require("../../assets/Cleaned_Products/NC Thin Arrowroot Biscuit.png"),
  "Nescafe Classic Jar": require("../../assets/Cleaned_Products/Nescafe Classic Jar.png"),
  "Nescafe Sunrise": require("../../assets/Cleaned_Products/Nescafe Sunrise.png"),
  "Nirmal Urutty Rose Rice": require("../../assets/Cleaned_Products/Nirmal Urutty Rose Rice.png"),
  "Pavithram Gingelly (Sesame) Oil": require("../../assets/Cleaned_Products/Pavithram Gingelly Sesame Oil.png"),
  "Pears Bathing Soap Oil Clear & Glow 75g": require("../../assets/Cleaned_Products/Pears Bathing Soap Oil Clear and Glow 75g.png"),
  "Pears Bathing Soap Pure & Gentle 60g": require("../../assets/Cleaned_Products/Pears Bathing Soap Pure and Gentle 60g.png"),
  "Pears Bathing Soap Soft & Fresh 100g": require("../../assets/Cleaned_Products/Pears Bathing Soap Soft and Fresh 100g.png"),
  "Pepsodent Toothpaste Germi Check Cavity Protection": require("../../assets/Cleaned_Products/Pepsodent Toothpaste Germi Check Cavity Protection.png"),
  "Pond's Facewash Men Energy Charge 50g": require("../../assets/Cleaned_Products/Pond's Facewash Men Energy Charge 50g.png"),
  "Pond's Facewash Pure White Anti Pollution 50g": require("../../assets/Cleaned_Products/Pond's Facewash Pure White Anti Pollution 50g.png"),
  "Pond's Facewash White Beauty Spot Less Fairness": require("../../assets/Cleaned_Products/Pond's Facewash White Beauty Spot Less Fairness.png"),
  "Pond's Pink Glow Face Talc 30g": require("../../assets/Cleaned_Products/Pond's Pink Glow Face Talc 30g.png"),
  "Pond's Talcum Powder Aloe 100g": require("../../assets/Cleaned_Products/Pond's Talcum Powder Aloe 100g.png"),
  "Pond's Talcum Powder Dreamflow 23g": require("../../assets/Cleaned_Products/Pond's Talcum Powder Dreamflow 23g.png"),
  "Pond's Talcum Powder Dreamflow Magic 20g": require("../../assets/Cleaned_Products/Pond's Talcum Powder Dreamflow Magic 20g.png"),
  "Ponds Aloe Cool 180g": require("../../assets/Cleaned_Products/Ponds Aloe Cool 180g.png"),
  "Potato": require("../../assets/Cleaned_Products/Potato.png"),
  "Prakrithi Coconut Oil": require("../../assets/Cleaned_Products/Prakrithi Coconut Oil.png"),
  "Pran Litchi Drink": require("../../assets/Cleaned_Products/Pran Litchi Drink.png"),
  "Pran Pudding Jar": require("../../assets/Cleaned_Products/Pran Pudding Jar.png"),
  "Premium Bake Rusk": require("../../assets/Cleaned_Products/Premium Bake Rusk.png"),
  "Pringles Desi Masala": require("../../assets/Cleaned_Products/Pringles Desi Masala.png"),
  "Pringles Original": require("../../assets/Cleaned_Products/Pringles Original.png"),
  "Pringles Sour & Cream": require("../../assets/Cleaned_Products/Pringles Sour and Cream.png"),
  "Pulari Rice Bran Oil": require("../../assets/Cleaned_Products/Pulari Rice Bran Oil.png"),
  "QK Multigrain Oats": require("../../assets/Cleaned_Products/QK Multigrain Oats.png"),
  "Quaker Oats": require("../../assets/Cleaned_Products/Quaker Oats.png"),
  "R.G. Palm Oil": require("../../assets/Cleaned_Products/R.G. Palm Oil.png"),
  "Raw Mango (Amrai)": require("../../assets/Cleaned_Products/Raw Mango Amrai.png"),
  "Red Chilly Sauce": require("../../assets/Cleaned_Products/Red Chilly Sauce.png"),
  "Red Label Tea Leaf Carton 250g": require("../../assets/Cleaned_Products/Red Label Tea Leaf Carton 250g.png"),
  "Red Label Tea Leaf Poly 100g": require("../../assets/Cleaned_Products/Red Label Tea Leaf Poly 100g.png"),
  "Red Label Tea Natural Care A Blend 250g": require("../../assets/Cleaned_Products/Red Label Tea Natural Care A Blend 250g.png"),
  "Red Masoor Dal": require("../../assets/Cleaned_Products/Red Masoor Dal.png"),
  "Rexona Bathing Soap Coconut And Olive Oil": require("../../assets/Cleaned_Products/Rexona Bathing Soap Coconut And Olive Oil.png"),
  "Rin Bleach Ala Bleach 200ml": require("../../assets/Cleaned_Products/Rin Bleach Ala Bleach 200ml.png"),
  "Rin Detergent Bar": require("../../assets/Cleaned_Products/Rin Detergent Bar.png"),
  "Rin Detergent Powder 1kg": require("../../assets/Cleaned_Products/Rin Detergent Powder 1kg.png"),
  "Rose Kaima Rice": require("../../assets/Cleaned_Products/Rose Kaima Rice.png"),
  "Ruchi Gold Palm Oil": require("../../assets/Cleaned_Products/Ruchi Gold Palm Oil.png"),
  "S S K Doppi Rice 1st": require("../../assets/Cleaned_Products/S S K Doppi Rice 1st.png"),
  "Sambar Powder": require("../../assets/Cleaned_Products/Sambar Powder.png"),
  "Santoor Soap (White/Set)": require("../../assets/Cleaned_Products/Santoor Soap White Set.png"),
  "Sara Soap Podi (washing powder)": require("../../assets/Cleaned_Products/Sara Soap Podi washing powder.png"),
  "Sarkara (Jaggery)": require("../../assets/Cleaned_Products/Sarkara Jaggery.png"),
  "Sensodyne Fresh Gel Paste": require("../../assets/Cleaned_Products/Sensodyne Fresh Gel Paste.png"),
  "Sensodyne Rapid Relief Paste": require("../../assets/Cleaned_Products/Sensodyne Rapid Relief Paste.png"),
  "Sensodyne Sensitive Toothbrush": require("../../assets/Cleaned_Products/Sensodyne Sensitive Toothbrush.png"),
  "Snickers": require("../../assets/Cleaned_Products/Snickers.png"),
  "SSK Ponni Rice 1st": require("../../assets/Cleaned_Products/SSK Ponni Rice 1st.png"),
  "Sunfeast Marie Glucose": require("../../assets/Cleaned_Products/Sunfeast Marie Glucose.png"),
  "Sunfeast Marie Light": require("../../assets/Cleaned_Products/Sunfeast Marie Light.png"),
  "Sunlight Detergent Powder": require("../../assets/Cleaned_Products/Sunlight Detergent Powder.png"),
  "Sunlight Dishwash Liquid": require("../../assets/Cleaned_Products/Sunlight Dishwash Liquid.png"),
  "Sunsilk Hair Conditioner Smooth & Tangle Free 80ml": require("../../assets/Cleaned_Products/Sunsilk Hair Conditioner Smooth and Tangle Free 80ml.png"),
  "Sunsilk Hair Shampoo Dream Soft & Smooth": require("../../assets/Cleaned_Products/Sunsilk Hair Shampoo Dream Soft and Smooth.png"),
  "Sunsilk Hair Shampoo Lusciously Thick & Long": require("../../assets/Cleaned_Products/Sunsilk Hair Shampoo Lusciously Thick and Long.png"),
  "Sunsilk Hair Shampoo Stunning Black Shine": require("../../assets/Cleaned_Products/Sunsilk Hair Shampoo Stunning Black Shine.png"),
  "Sunsilk Thick & Long Twin (5.5+5.5)ml": require("../../assets/Cleaned_Products/Sunsilk Thick and Long Twin 5.5 Plus 5.5ml.png"),
  "Surf Excel Detergent Bar 100g": require("../../assets/Cleaned_Products/Surf Excel Detergent Bar 100g.png"),
  "Surf Excel Detergent Liquid Easy Wash 500ml": require("../../assets/Cleaned_Products/Surf Excel Detergent Liquid Easy Wash 500ml.png"),
  "Surf Excel Detergent Liquid Matic Front Load Refill": require("../../assets/Cleaned_Products/Surf Excel Detergent Liquid Matic Front Load Refill.png"),
  "Surf Excel Detergent Liquid Matic Top Load Refill": require("../../assets/Cleaned_Products/Surf Excel Detergent Liquid Matic Top Load Refill.png"),
  "Surf Excel Detergent Powder Easy Wash": require("../../assets/Cleaned_Products/Surf Excel Detergent Powder Easy Wash.png"),
  "Surf Excel Detergent Powder Quick Wash 1kg": require("../../assets/Cleaned_Products/Surf Excel Detergent Powder Quick Wash 1kg.png"),
  "Taaza Elaichi 250g": require("../../assets/Cleaned_Products/Taaza Elaichi 250g.png"),
  "Taaza Tea 100g": require("../../assets/Cleaned_Products/Taaza Tea 100g.png"),
  "Taaza Tea Masala Chaska Elaichi 250g": require("../../assets/Cleaned_Products/Taaza Tea Masala Chaska Elaichi 250g.png"),
  "Taj Mahal Tea Leaf 100g": require("../../assets/Cleaned_Products/Taj Mahal Tea Leaf 100g.png"),
  "Tiger Krunch Choco": require("../../assets/Cleaned_Products/Tiger Krunch Choco.png"),
  "TRESemme Hair Conditioner Hair Fall Defense": require("../../assets/Cleaned_Products/TRESemme Hair Conditioner Hair Fall Defense.png"),
  "TRESemme Hair Conditioner Keratin Smooth": require("../../assets/Cleaned_Products/TRESemme Hair Conditioner Keratin Smooth.png"),
  "TRESemme Hair Conditioner Smooth & Shine": require("../../assets/Cleaned_Products/TRESemme Hair Conditioner Smooth and Shine.png"),
  "TRESemme Hair Shampoo Hair Fall Defense 6ml": require("../../assets/Cleaned_Products/TRESemme Hair Shampoo Hair Fall Defense 6ml.png"),
  "TRESemme Hair Shampoo Keratin Smooth 6ml": require("../../assets/Cleaned_Products/TRESemme Hair Shampoo Keratin Smooth 6ml.png"),
  "TRESemme Smooth & Shine LCS 6ml": require("../../assets/Cleaned_Products/TRESemme Smooth and Shine LCS 6ml.png"),
  "True Blue Dragon Noodles": require("../../assets/Cleaned_Products/True Blue Dragon Noodles.png"),
  "TT Asafoetida (Kayam)": require("../../assets/Cleaned_Products/TT Asafoetida Kayam.png"),
  "Turmeric Powder": require("../../assets/Cleaned_Products/Turmeric Powder.png"),
  "Ujala Crystal White Liquid": require("../../assets/Cleaned_Products/Ujala Crystal White Liquid.png"),
  "Ujala Y&F Bliss/Aura Sachet": require("../../assets/Cleaned_Products/Ujala Y and F Bliss Aura Sachet.png"),
  "UT Appam Podi": require("../../assets/Cleaned_Products/UT Appam Podi.png"),
  "UT Puttu Podi": require("../../assets/Cleaned_Products/UT Puttu Podi.png"),
  "UT Uppuma Rava": require("../../assets/Cleaned_Products/UT Uppuma Rava.png"),
  "V Wash Plus 100ml": require("../../assets/Cleaned_Products/V Wash Plus 100ml.png"),
  "Vim Bar 3x190g MPO": require("../../assets/Cleaned_Products/Vim Bar 3x190g MPO.png"),
  "Vim Bar Tubs Anti-Smell 500g": require("../../assets/Cleaned_Products/Vim Bar Tubs Anti-Smell 500g.png"),
  "Vim Dishwash Bar 75g": require("../../assets/Cleaned_Products/Vim Dishwash Bar 75g.png"),
  "Vim Dishwash Bar Tub 500g": require("../../assets/Cleaned_Products/Vim Dishwash Bar Tub 500g.png"),
  "Vim Dishwash Gel Liquid Lemon 115ml": require("../../assets/Cleaned_Products/Vim Dishwash Gel Liquid Lemon 115ml.png"),
  "Vim Dishwash Gel Liquid Lemon 250ml": require("../../assets/Cleaned_Products/Vim Dishwash Gel Liquid Lemon 250ml.png"),
  "Vivel / Fiama products (assorted)": require("../../assets/Cleaned_Products/Vivel Fiama products assorted.png"),
  "Wheel Detergent Powder Blue 1kg": require("../../assets/Cleaned_Products/Wheel Detergent Powder Blue 1kg.png"),
  "Wheel L&O Powder A+ 4kg Blue": require("../../assets/Cleaned_Products/Wheel L and O Powder A Plus 4kg Blue.png"),
  "Women's Horlicks Caramel Pet Jar 400g": require("../../assets/Cleaned_Products/Women's Horlicks Caramel Pet Jar 400g.png"),
  "Yardley English Rose Talc": require("../../assets/Cleaned_Products/Yardley English Rose Talc.png"),
  "Yardley Lavender Talc": require("../../assets/Cleaned_Products/Yardley Lavender Talc.png"),
  "Yardley Red Rose Talc": require("../../assets/Cleaned_Products/Yardley Red Rose Talc.png"),
  "Yippee Magic Masala Noodles": require("../../assets/Cleaned_Products/Yippee Magic Masala Noodles.png"),
};

// Every seeded product's `images` array is empty ([]) unless an admin has uploaded a
// real photo through the admin portal's ProductForm — that's how we tell "no admin photo
// yet" apart from "a real photo someone deliberately uploaded."
const GENERIC_STOCK_PHOTO = /res\.cloudinary\.com\/demo\//;

// Resolves the best available image source for a product:
//  1. A real admin-uploaded photo (item.images[0], if not the generic seed stock photo)
//     — lets an admin replace a product's picture (e.g. new packaging) without an app
//     rebuild, since this is just a live Firestore field, unlike the bundled ones below.
//     Rewritten through optimizeCloudinaryUrl() so the app decodes a ~width-sized image
//     instead of Cloudinary's raw full-resolution upload — this is the fix for slow image
//     loading, since most catalog products go through this admin-uploaded path.
//  2. A locally-bundled require() asset for this exact product name (this file).
//  3. The (possibly still-generic) remote URL, so something shows rather than nothing.
//  4. null — caller renders its own empty-state icon.
//
// `width` defaults to cover the biggest product-card box in the app (grid/list cards are
// ~96-150px, but phones commonly run 2-3x pixel density) — pass a larger value for a
// full-width hero image (e.g. ProductDetailScreen).
export function getProductImageSource(item, width = 320) {
  const uri = item?.images?.[0];
  if (uri && !GENERIC_STOCK_PHOTO.test(uri)) return { uri: optimizeCloudinaryUrl(uri, width) };
  const local = item?.name ? productImages[item.name] : undefined;
  if (local) return local;
  return uri ? { uri: optimizeCloudinaryUrl(uri, width) } : null;
}

export default productImages;
